spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

security:
  secretkey: ${JWT_SECRET_KEY}
